tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-error": "#490013",
                "surface-bright": "#2c2c30",
                "tertiary-fixed-dim": "#00e5ee",
                "tertiary": "#a1faff",
                "inverse-on-surface": "#555458",
                "tertiary-dim": "#00e5ee",
                "on-secondary-fixed": "#6e0028",
                "error-dim": "#d73357",
                "surface-container-low": "#131316",
                "surface-container": "#19191d",
                "primary-fixed": "#819bff",
                "on-tertiary": "#006165",
                "primary-dim": "#3467ff",
                "primary-fixed-dim": "#6c8cff",
                "surface-dim": "#0e0e11",
                "on-secondary-container": "#fff6f5",
                "tertiary-container": "#00f4fe",
                "error": "#ff6e84",
                "secondary-dim": "#e2165f",
                "on-primary-fixed": "#000000",
                "on-tertiary-container": "#00575b",
                "on-surface-variant": "#acaaae",
                "background": "#0e0e11",
                "primary-container": "#819bff",
                "surface": "#0e0e11",
                "surface-container-high": "#1f1f23",
                "on-secondary-fixed-variant": "#a30040",
                "on-primary": "#00257c",
                "inverse-primary": "#004eeb",
                "outline": "#767579",
                "secondary": "#fe018d",
                "on-tertiary-fixed": "#004346",
                "on-primary-container": "#001b61",
                "surface-container-highest": "#25252a",
                "tertiary-fixed": "#00f4fe",
                "on-error-container": "#ffb2b9",
                "surface-variant": "#25252a",
                "primary": "#94aaff",
                "on-secondary": "#480018",
                "secondary-container": "#bc004b",
                "on-tertiary-fixed-variant": "#006266",
                "on-primary-fixed-variant": "#002376",
                "secondary-fixed": "#ffc2ca",
                "on-background": "#f0edf1",
                "on-surface": "#f0edf1",
                "surface-tint": "#94aaff",
                "outline-variant": "#48474b",
                "error-container": "#a70138",
                "inverse-surface": "#fcf8fd",
                "secondary-fixed-dim": "#ffaeba"
            },
            fontFamily: {
                "headline": ["Epilogue"],
                "body": ["Space Grotesk"],
                "label": ["Space Grotesk"],
                "ade": ["Ade Display", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
};
